### ISSUE TITLE
Make doesn't compile fmindex_search_pigeon.cpp changes

### ISSUE THREAD

**Issue by fischer-hub** [SGSSGene/ImplementingSearch#4]
When fmindex_search_pigeon.cpp is changed `make` compiles fmindex_search.cpp instead of fmindex_search_pigeon.cpp.

Should this [line](https://github.com/SGSSGene/ImplementingSearch/blob/main/src/CMakeLists.txt#L19) maybe say `add_executable (fmindex_pigeon_search fmindex_pigeon_search.cpp)` ?

**Comment by SGSSGene** [comment]
Ah, yes! you are right!
